### ISSUE TITLE
印刷ページの物品貸出表のcsv出力を修正する

### ISSUE THREAD

**Issue by harata-t** [NUTFes/group-manager-2#1668]
# 開発目的

500 Internal Server Error

<img width="751" height="936" alt="Image" src="https://github.com/user-attachments/assets/851de12d-300a-492e-afe3-ae65aa2308a6" />

```
API             | Started GET "/api/v1/get_assign_rental_items_csv/2" for 192.168.65.1 at 2025-11-04 03:58:36 +0000
API             | Processing by Api::V1::OutputCsvController#output_assign_rental_items_csv as HTML
API             |   Parameters: {"fes_year_id"=>"2"}
API             |   User Load (2.8ms)  SELECT `users`.* FROM `users` WHERE `users`.`uid` = 'nutfes-taro@email.com' LIMIT 1
API             |   FesYear Load (0.5ms)  SELECT `fes_years`.* FROM `fes_years` WHERE `fes_years`.`id` = 2 LIMIT 1
API             |   ↳ app/controllers/api/v1/output_csv_controller.rb:46:in `output_assign_rental_items_csv'
API             | Completed 500 Internal Server Error in 8ms (ActiveRecord: 3.3ms | Allocations: 1960)
API             | 
API             | 
API             |   
API             | IOError (not opened for writing):
API             |   
API             | app/controllers/api/v1/output_csv_controller.rb:52:in `block in output_assign_rental_items_csv'
API             | app/controllers/api/v1/output_csv_controller.rb:49:in `output_assign_rental_items_csv'
```

# 考えられる開発内容

# 考えられる開発時間

# 備考

**Comment by batcho0428** [comment]
出力しようとするとエラーが出る
